spring:
  data:
    mongodb:
      host: localhost
      database: reactiveDB

server:
  servlet:
    context-path: /reactive

  port: 9000

logging:
  file:
    path: /var/log
    name: reactive.log
  level: info
