spring:
  data:
    mongodb:
      host: localhost
      database: reactiveDB
  security:
    user:
      name: zjh
      password: password

server:
  servlet:
    context-path: /reactive
  port: 9000

logging:
  file: /home/zjh/logs/reactive.log
  level:
    com.zjh.reactive: info
